In [1]:
import numpy as np

In [3]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a=np.array([[1,2,3],
            [4,5,6]])
print(a.ndim) # Number of dimensions of the array
print(a.shape) # Number of rows and columns
print(a.dtype) # Datatype of the array
print(a.size) # Number of elements in the array
print(a.itemsize) # Size of the array element in bytes

2
(2, 3)
int64
6
8


In [ ]:
a=np.zeros((3,3)) # Prints a 3x3 matrix of zeroes
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
ones=np.ones((2,4)) # Prints a matrix full of 1's (default float values if no datatype specified)
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
a=np.full((4,2),19,dtype=int) #  Fills the matrix with the given value
a

array([[19, 19],
       [19, 19],
       [19, 19],
       [19, 19]])

In [22]:
# Transposing Matrices
a=np.array([[7,8,9],[4,7,3]])
transpose=a.T
transpose

array([[7, 4],
       [8, 7],
       [9, 3]])

In [30]:
a=np.array([[1,2],[5,8],[7,9]])
swapped=a.swapaxes(1,0)
swapped

array([[1, 5, 7],
       [2, 8, 9]])

In [ ]:
# Random number generation
r=np.random.randint(1,10,size=(3,3)) # Generates a 3x3 matrix with random numbers between the given range
print(r)
n=np.random.normal(1,5,size=(2,2)) # Generates a matrix of random distribution
print(n)

[[1 2 4]
 [1 4 6]
 [3 8 7]]
[[-0.95215434 -2.62696201]
 [ 3.64173409  4.46213667]]


In [ ]:
# Matrix multiplication
matrix_1=np.array([[1,2],[5,6]])
matrix_2=np.array([[9,7],[7,3]])
mul=np.matmul(matrix_1,matrix_2)
print(mul)

[[23 13]
 [87 53]]


In [35]:
# Reshaping a 1-dimensional array to a matrix
arr=np.array([1,2,3,4,5,6,7,8,9])
res=arr.reshape(3,3)
print(res)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
# Aggregate functions
max=np.max(res)
min=np.min(res)
sum=np.sum(res)
mean=np.mean(res)
print(sum)
print(min)
print(max)
print(mean)

45
1
9
5.0
